# .pages.yml

# Media settings for your images
media:
  - name: ais_images
    label: AIS Images
    input: static/images/ais
    output: /images/ais
    extensions: [png, jpg, webp, gif]

  - name: aprs_images
    label: APRS Images
    input: static/images/aprs
    output: /images/aprs
    extensions: [png, jpg, webp, gif]

  - name: meshcore_images
    label: Meshcore Images
    input: static/images/meshcore
    output: /images/meshcore
    extensions: [png, jpg, webp, gif]
    
  - name: general_images
    label: General Images
    input: static/images
    output: /images
    extensions: [png, jpg, webp, gif]
    
     
# Content collections mapping
content:
  - name: aprs
    label: APRS
    path: content/aprs
    type: collection
    fields: &default_fields
      - name: title
        label: Title
        type: string
      - name: subtitle
        label: Subtitle
        type: string
      - name: date
        label: Date
        type: date
      - name: tags
        label: Tags
        type: string
        list: true
      - name: author
        label: Author
        type: string
      - name: draft
        label: Draft
        type: boolean
      - name: body
        label: Content
        type: rich-text

  - name: ais
    label: AIS
    path: content/ais
    type: collection
    fields: *default_fields

  - name: meshcore
    label: Meshcore
    path: content/meshcore
    type: collection
    fields: *default_fields

  - name: page
    label: Pages
    path: content/page
    type: collection
    fields: *default_fields

  - name: post
    label: Posts
    path: content/post
    type: collection
    fields: *default_fields
    